### ISSUE TITLE
S3 Mount

### ISSUE THREAD

**Issue by RendinaFTI** [fti-sc/jupyter-template#1]
Per Ian:
A nice-to-have, but certainly not a necessity. Would be nice to pull data from S3 without using Boto3.

https://github.com/s3fs-fuse/s3fs-fuse

**Comment by RendinaFTI** [comment]
Broke my mac's docker desktop... putting this aside as boto3 is still an acceptable API... we can build our own PYPI package or develop an API to speed up our development with S3 and other data source querying

**Comment by dawidfti** [comment]
On a separate note, if we end up with DVC for versioning data, pulling data from S3 would be automated with the tool once it is set up.

**Comment by RendinaFTI** [comment]
DVC option, not worth avoiding Boto3 at this point
